package tdk_enum.common.configuration.config_types;

public enum MLModelType {

    COMBINED, GAUSSIAN_PROCESSES, ISOTONIC_REGRESSION, LEAST_MED_SQ, LINEAR_REGRESSION, MULTILAYER_PERCEPTRON,
    PACE_REGRESSION, PLS_CLASSIFIER, SMOREG, IBK, KSTAR, LWL, ADDITIVE_REGRESSION, BAGGING, CV_PARAMETER_SELECTION,
    M5RULES, M5P
}
